### PR TITLE
1.7.4 fixes

### LINKED ISSUE #217: [1.7.4] Planned improvements
- [ ] Port DW NFT's description overflow behaviour
- [x] AddessInfoPage: check whether the addressHash from useParams is a valid address before using it apart from whether it exists or not. Add the address validity check in the enabled flags of each query so that we avoid spamming the server with unnecessary requests when the address is invalid.
- [x] Remove axios from the deps (why the heck is it still here :P)
- [x] Create alphMetadata util object: `const alphMetadata = { ...ALPH, type: 'fungible', verified: true } as VerifiedFungibleTokenMetadata`
- [x] Amount.tsx: update suffix list based on sdk recent change
- [x] AssetLogo: handle potential failure of JSON.parse
- [x] staticDataContext: Make type more explicit: `<Map<Asset['id'], VerifiedFungibleTokenMetadata>>`
- [x] useTraceUpdate: remove es-lint disable

### PR DESCRIPTION
**Pull request by mvaivre**
Fixes #217

### CODE REVIEW

File: src/components/Amount.tsx [hunk 1]
```diff
@@ -75,7 +75,7 @@ const Amount = ({
     if (value !== undefined) {
       amount = getAmount({ value, isFiat, decimals, nbOfDecimalsToShow, fullPrecision })
 
-      if (fadeDecimals && ['K', 'M', 'B', 'T'].some((char) => amount.endsWith(char))) {
+      if (fadeDecimals && MAGNITUDE_SYMBOL.some((char) => amount.endsWith(char))) {
```
Comment (nop33) [inline src/components/Amount.tsx:78]: Does the fact that `MAGNITUDE_SYMBOL` includes an empty string (`''`) affect this in any way?

**Review by nop33 — APPROVED** [review]

File: src/components/Amount.tsx (hunk 1 above)
Comment (mvaivre) [reply src/components/Amount.tsx:78]: Such a great catch. I think it may affect this, indeed. We should probably export only the actual symbols from the js-sdk.

Comment (mvaivre) [reply src/components/Amount.tsx:78]: https://github.com/alephium/js-sdk/pull/158

**Comment by mvaivre** [comment]
Just need to use sdk 0.7.5 & merge
